In [11]:
from tensorflow.keras.preprocessing.text import one_hot

In [12]:
#sentences
sent=['the glass of milk',
      'the glass of juice',
      'the cup of tea',
      'I am a good boy',
      'I am a good developer',
      'understand the meaning of words',
      'your videos are good'
      ]

In [13]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [14]:
#Define the vocabulary size
voc_size=10000

In [15]:
#One hot Representation
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[639, 2458, 1324, 316],
 [639, 2458, 1324, 8218],
 [639, 7084, 1324, 6050],
 [2577, 7401, 9009, 1455, 8631],
 [2577, 7401, 9009, 1455, 7854],
 [6218, 639, 4415, 1324, 426],
 [1229, 4358, 1517, 1455]]

In [16]:
#Word Embedding Representation
from tensorflow.keras.layers import Embedding
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [17]:
import numpy as np

In [18]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0  639 2458 1324  316]
 [   0    0    0    0  639 2458 1324 8218]
 [   0    0    0    0  639 7084 1324 6050]
 [   0    0    0 2577 7401 9009 1455 8631]
 [   0    0    0 2577 7401 9009 1455 7854]
 [   0    0    0 6218  639 4415 1324  426]
 [   0    0    0    0 1229 4358 1517 1455]]


In [19]:
#feature representation
dim=10

In [20]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

In [21]:
model.summary()

Model: "sequential_3"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             100000    
                                                                 
Total params: 100000 (390.62 KB)
Trainable params: 100000 (390.62 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [23]:
model.predict(embedded_docs[0])

1/1 [==============================] - 0s 97ms/step


array([[ 0.01948098, -0.03876277, -0.03694236,  0.02713982,  0.01870085,
        -0.02147256,  0.03557153,  0.0160293 ,  0.03439924, -0.04835867],
       [ 0.01948098, -0.03876277, -0.03694236,  0.02713982,  0.01870085,
        -0.02147256,  0.03557153,  0.0160293 ,  0.03439924, -0.04835867],
       [ 0.01948098, -0.03876277, -0.03694236,  0.02713982,  0.01870085,
        -0.02147256,  0.03557153,  0.0160293 ,  0.03439924, -0.04835867],
       [ 0.01948098, -0.03876277, -0.03694236,  0.02713982,  0.01870085,
        -0.02147256,  0.03557153,  0.0160293 ,  0.03439924, -0.04835867],
       [ 0.01262504,  0.01391326, -0.0131377 , -0.01027052, -0.0401276 ,
         0.03378499, -0.02131655,  0.04505856,  0.04604951, -0.04504865],
       [ 0.03771919, -0.0271173 , -0.00648885,  0.00858523, -0.01356913,
        -0.04555069,  0.02033817,  0.03473187,  0.02574674, -0.00969583],
       [ 0.01220185, -0.03991164,  0.00355619,  0.02320326, -0.02020737,
         0.02830182,  0.01373038,  0.01999963